
# set variable needed at detector configuration first:
/analysis/pixel_depletion 30.0
/analysis/pixel_width 1.4
/analysis/pixel_max_x 2
/analysis/pixel_max_y 2
/analysis/gun_theta 0.1

# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
/control/execute vis.mac
# 
# gamma 1 MeV to the direction (0.,0.,1.)
#
/gun/particle gamma
/gun/energy 500 keV
#
#/run/beamOn 10000000
/run/beamOn 10
