
# set variable needed at detector configuration first:
/analysis/pixel_depth 20.0
/analysis/pixel_depletion 3.0
/analysis/pixel_width 100.12
/analysis/pixel_max_x 0
/analysis/pixel_max_y 0
/analysis/gen_theta 0.0
/analysis/gen_theta_max 0.0
/analysis/gen_phi_max 0.0

# Initialize kernel
/run/initialize
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# gamma 1 MeV to the direction (0.,0.,1.)
#
/gun/particle gamma
/gun/energy 1000 keV
#
/run/beamOn 100000000
